# Generated by Django 4.2.16 on 2024-10-15 09:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookcopy_remove_borrow_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies_available',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book_copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bookcopy'),
        ),
    ]
